### ISSUE TITLE
fill in a definition for encapsulation in OOP 

### ISSUE THREAD

**Issue by hoasung01** [hoasung01/SharingKnowledge#14]
- should place under `~/OOP/Principles`
- and using this below format as example
 ```ruby
class Encapsulation
   def define
     <<~DEFINE.strip
       # your definition here
     DEFINE
   end
end
 ```

**Comment by rparthas** [comment]
@hoasung01  Created pull request for the same https://github.com/hoasung01/SharingKnowledge/pull/20
