### ISSUE TITLE
fill in a definition for inheritance in OOP

### ISSUE THREAD

**Issue by hoasung01** [hoasung01/SharingKnowledge#15]
- should place under `~/OOP/Principles`
- and using this below format as example
 ```ruby
class Inheritance
   def define
     <<~DEFINE.strip
       # your definition here
     DEFINE
   end
end
 ```

**Comment by AndroidonEarth** [comment]
I'd like to take this one as well :)

I already made a PR #19 

Thanks!

**Comment by hoasung01** [comment]
- thanks @AndroidonEarth  a lot 
- I will close this issue because someone sent and I merged it already :)
